In [1]:
%matplotlib notebook
import os
import pandas as pd
import numpy as np

In [2]:
# File to Load (Remember to Change These)
file_to_load = "../../Resources/casos-asociados-a-covid-19.csv"

# Read Purchasing File and store into Pandas data frame
covid_cases_data = pd.read_csv(file_to_load)
covid_cases_data.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (30,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,FECHA ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD UNIDAD MEDICA,SEXO,ENTIDAD NACIMIENTO,ENTIDAD RESIDENCIA,MUNICIPIO RESIDENCIA,TIPO PACIENTE,...,Negativo,MIGRANTE,PAIS NACIONALIDAD,PAIS ORIGEN,UNIDAD DE CUIDADOS INTENSIVOS,RANGO EDAD,num_fallecidos,num_hospitalizados,positivo,pendiente
0,2020-06-24,076847,USMER,SSA,PUEBLA,MUJER,PUEBLA,PUEBLA,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,31-40,NaN,NaN,Positivo SARS-CoV-2,NaN
1,2020-06-24,0f2b37,USMER,SSA,CHIAPAS,HOMBRE,CHIAPAS,CHIAPAS,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,31-40,NaN,NaN,Positivo SARS-CoV-2,NaN
2,2020-06-24,1aa59e,USMER,SSA,VERACRUZ DE IGNACIO DE LA LLAVE,MUJER,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ DE IGNACIO DE LA LLAVE,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,41-50,NaN,NaN,Positivo SARS-CoV-2,NaN
3,2020-06-24,190217,USMER,SSA,SONORA,MUJER,SONORA,SONORA,NaN,HOSPITALIZADO,...,NaN,NO ESPECIFICADO,México,99,NO,41-50,NaN,1.0,Positivo SARS-CoV-2,NaN
4,2020-06-24,169761,USMER,SSA,YUCATÁN,HOMBRE,YUCATÁN,YUCATÁN,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,31-40,NaN,NaN,Positivo SARS-CoV-2,NaN

In [3]:
clean_covid_data = covid_cases_data[["ID_REGISTRO","SEXO","FECHA INGRESO", "FECHA DEFUNCION","INTUBADO","EDAD","DIABETES","EPOC","ASMA","INMUNOSUPRESION","HIPERTENSION","CARDIOVASCULAR","OBESIDAD","RENAL CRONICA","TABAQUISMO"]]
display(clean_covid_data)

,ID_REGISTRO,SEXO,FECHA INGRESO,FECHA DEFUNCION,INTUBADO,EDAD,DIABETES,EPOC,ASMA,INMUNOSUPRESION,HIPERTENSION,CARDIOVASCULAR,OBESIDAD,RENAL CRONICA,TABAQUISMO
0,076847,MUJER,2020-06-01,NaN,NO APLICA,36,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,0f2b37,HOMBRE,2020-06-02,NaN,NO APLICA,32,NO,NO,NO,NO,NO,NO,NO,NO,NO
2,1aa59e,MUJER,2020-06-15,NaN,NO APLICA,43,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,190217,MUJER,2020-06-13,NaN,NO,42,NO,NO,NO,NO,SI,NO,NO,NO,NO
4,169761,HOMBRE,2020-06-16,NaN,NO APLICA,33,NO,NO,NO,NO,NO,NO,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515653,1b2821,MUJER,2020-04-24,NaN,NO APLICA,49,NO,NO,NO,NO,NO,NO,NO,NO,SI
515654,1c1174,MUJER,2020-06-09,NaN,NO APLICA,53,NO,NO,NO,NO,NO,NO,NO,NO,NO
515655,1a1c43,MUJER,2020-06-10,NaN,NO APLICA,32,NO,NO,NO,NO,NO,NO,NO,NO,NO
515656,062e79,MUJER,2020-06-10,NaN,NO APLICA,44,NO,NO,NO,NO,NO,NO,SI,NO,NO
515657,123e91,MUJER,2020-06-06,NaN,NO APLICA,29,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [4]:
cases_per_date = clean_covid_data.copy()
cases_per_date = cases_per_date.groupby(['FECHA INGRESO']).count().rename(columns={'ID_REGISTRO':'CASOS'}).drop(['SEXO','FECHA DEFUNCION','INTUBADO','EDAD','DIABETES','EPOC','ASMA','INMUNOSUPRESION','HIPERTENSION','CARDIOVASCULAR','OBESIDAD','RENAL CRONICA','TABAQUISMO'],axis=1).reset_index()
cases_per_date

    FECHA INGRESO  CASOS
0      2020-01-01      5
1      2020-01-02     16
2      2020-01-03     18
3      2020-01-04      6
4      2020-01-05     14
..            ...    ...
171    2020-06-20   5710
172    2020-06-21   3752
173    2020-06-22  11629
174    2020-06-23  11098
175    2020-06-24   4763

[176 rows x 2 columns]

In [5]:
pd.DataFrame.to_csv(cases_per_date,'../assets/data/casos_fecha_ingreso.csv',encoding='latin1')