In [1]:
%matplotlib notebook
import os
import pandas as pd
import numpy as np
import pymongo

In [2]:
file_to_load = "../../Resources/casos-asociados-a-covid-19.csv"

covid_cases_data = pd.read_csv(file_to_load)
covid_cases_data.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (30,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,FECHA ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD UNIDAD MEDICA,SEXO,ENTIDAD NACIMIENTO,ENTIDAD RESIDENCIA,MUNICIPIO RESIDENCIA,TIPO PACIENTE,...,Negativo,MIGRANTE,PAIS NACIONALIDAD,PAIS ORIGEN,UNIDAD DE CUIDADOS INTENSIVOS,RANGO EDAD,num_fallecidos,num_hospitalizados,positivo,pendiente
0,2020-06-30,05043b,FUERA DE USMER,SSA,OAXACA,HOMBRE,OAXACA,OAXACA,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,41-50,NaN,NaN,Positivo SARS-CoV-2,NaN
1,2020-06-30,12ea72,FUERA DE USMER,SSA,JALISCO,HOMBRE,CHIAPAS,JALISCO,Álvaro Obregón,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,21-30,NaN,NaN,Positivo SARS-CoV-2,NaN
2,2020-06-30,1b728d,FUERA DE USMER,SSA,CIUDAD DE MÉXICO,MUJER,OAXACA,CIUDAD DE MÉXICO,Tlalpan,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,51-60,NaN,NaN,Positivo SARS-CoV-2,NaN
3,2020-06-30,197843,FUERA DE USMER,SSA,OAXACA,HOMBRE,OAXACA,OAXACA,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,61-70,NaN,NaN,Positivo SARS-CoV-2,NaN
4,2020-06-30,0eebc6,FUERA DE USMER,SSA,VERACRUZ DE IGNACIO DE LA LLAVE,HOMBRE,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ DE IGNACIO DE LA LLAVE,NaN,AMBULATORIO,...,NaN,NO ESPECIFICADO,México,99,NO APLICA,31-40,NaN,NaN,Positivo SARS-CoV-2,NaN

In [3]:
clean_covid_data = covid_cases_data[covid_cases_data["positivo"]!="Positivo SARS-CoV-2"]
clean_covid_data = clean_covid_data[["ID_REGISTRO","SEXO","MUNICIPIO RESIDENCIA","FECHA INGRESO", "FECHA DEFUNCION","INTUBADO","EDAD","DIABETES","EPOC","ASMA","INMUNOSUPRESION","HIPERTENSION","CARDIOVASCULAR","OBESIDAD","RENAL CRONICA","TABAQUISMO"]]
clean_covid_data = clean_covid_data.fillna("NO")
display(clean_covid_data)

,ID_REGISTRO,SEXO,MUNICIPIO RESIDENCIA,FECHA INGRESO,FECHA DEFUNCION,INTUBADO,EDAD,DIABETES,EPOC,ASMA,INMUNOSUPRESION,HIPERTENSION,CARDIOVASCULAR,OBESIDAD,RENAL CRONICA,TABAQUISMO
43900,1b6127,MUJER,Cuajimalpa de Morelos,2020-06-25,NO,NO APLICA,37,NO,NO,NO,NO,NO,NO,NO,NO,NO
43901,0abd68,HOMBRE,Tlalpan,2020-03-20,NO,NO APLICA,27,NO,NO,NO,NO,NO,NO,NO,NO,NO
43902,07e1a5,HOMBRE,NO,2020-04-01,2020-04-09,NO,52,NO,NO,NO,NO,NO,NO,NO,NO,NO
43903,0f9fb2,MUJER,Xochimilco,2020-03-27,NO,NO APLICA,27,NO,NO,NO,NO,NO,NO,SI,NO,NO
43904,0749a5,HOMBRE,Gustavo A. Madero,2020-03-24,NO,NO,4,NO,NO,NO,NO,NO,NO,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581575,15a279,HOMBRE,NO,2020-06-21,NO,NO APLICA,25,NO,NO,NO,NO,NO,NO,NO,NO,NO
581576,027071,HOMBRE,NO,2020-06-25,2020-06-25,NO,42,NO,NO,SI,NO,SI,NO,NO,NO,NO
581577,1714f1,MUJER,NO,2020-06-25,NO,NO APLICA,44,NO,NO,NO,NO,NO,NO,NO,NO,NO
581578,0db987,MUJER,NO,2020-06-25,NO,NO APLICA,29,NO,NO,NO,NO,NO,NO,NO,NO,NO
581579,0611d4,MUJER,NO,2020-06-26,NO,NO APLICA,57,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [4]:
generos = ["TODOS","MUJER","HOMBRE"]
condiciones = ["TODOS","SIN CONDICION","DIABETES","EPOC","ASMA","INMUNOSUPRESION","HIPERTENSION","CARDIOVASCULAR","OBESIDAD","RENAL CRONICA","TABAQUISMO"]
datos = ["TODOS","INTUBADOS","DIFUNTOS"]
bins = [-1, 15, 20, 30, 40, 50, 60, 70, 80, 90, 999]
group_labels=['0-15','16-20','21-30','31-40','41-50','51-60','61-70','71-80','81-90','91+']
enfermedades_edades = pd.DataFrame(columns=['RANGO DE EDAD'], data=group_labels)
for condicion in condiciones:
    resumen = clean_covid_data.copy()
    if condicion != "TODOS":
        if condicion == "SIN CONDICION":
            resumen = resumen[(resumen['DIABETES']=="NO") & (resumen['TABAQUISMO']=="NO") & (resumen['EPOC']=="NO") & (resumen['ASMA']=="NO") & (resumen['INMUNOSUPRESION']=="NO") & (resumen['HIPERTENSION']=="NO") & (resumen['CARDIOVASCULAR']=="NO") & (resumen['RENAL CRONICA']=="NO") & (resumen['OBESIDAD']=="NO")]
        else:
            resumen = resumen[resumen[condicion]=="SI"]
    resumen["RANGO DE EDAD"] = pd.cut(resumen["EDAD"], bins, labels=group_labels)
    resumen = resumen.groupby(['RANGO DE EDAD']).count().drop(['SEXO','FECHA DEFUNCION','MUNICIPIO RESIDENCIA','FECHA INGRESO','INTUBADO','EDAD','DIABETES','EPOC','ASMA','INMUNOSUPRESION','HIPERTENSION','CARDIOVASCULAR','OBESIDAD','RENAL CRONICA','TABAQUISMO'],axis=1).rename(columns={'ID_REGISTRO':f'{condicion}'}).reset_index()
    enfermedades_edades = enfermedades_edades.merge(resumen, how='left', on='RANGO DE EDAD')
display(enfermedades_edades)

,RANGO DE EDAD,TODOS,SIN CONDICION,DIABETES,EPOC,ASMA,INMUNOSUPRESION,HIPERTENSION,CARDIOVASCULAR,OBESIDAD,RENAL CRONICA,TABAQUISMO
0,0-15,16856,14649,105,26,606,720,114,323,380,115,91
1,16-20,10461,8478,90,23,454,191,114,76,619,106,631
2,21-30,72610,54663,919,136,2841,663,1742,454,7337,616,7236
3,31-40,89633,61716,3139,253,3228,954,5148,806,13170,795,9148
4,41-50,75304,45011,7653,532,2666,1048,10702,1151,13388,988,6357
5,51-60,48917,23619,9990,873,1371,991,12871,1408,9013,1396,4105
6,61-70,23642,8394,7639,1200,618,797,9623,1416,4147,1375,2196
7,71-80,11755,3121,4301,1262,306,460,6049,1260,1805,816,1239
8,81-90,5283,1375,1587,862,115,195,2826,743,555,381,526
9,91+,1030,354,193,205,24,31,436,145,54,55,86

In [5]:
pd.DataFrame.to_csv(enfermedades_edades,'../static/data/enfermedades_edades.csv',encoding='latin1')
enfermedades_edades.to_json('../static/data/enfermedades_edades.json',orient='records')

In [6]:
generos = ["TODOS","MUJER","HOMBRE"]
condiciones = ["TODOS","SIN CONDICION","DIABETES","EPOC","ASMA","INMUNOSUPRESION","HIPERTENSION","CARDIOVASCULAR","OBESIDAD","RENAL CRONICA","TABAQUISMO"]
datos = ["TODOS","INTUBADOS","DIFUNTOS"]
enfermedades_genero = pd.DataFrame(columns=['SEXO'], data=clean_covid_data['SEXO'].unique().tolist())
for condicion in condiciones:
    resumen = clean_covid_data.copy()
    if condicion != "TODOS":
        if condicion == "SIN CONDICION":
            resumen = resumen[(resumen['DIABETES']=="NO") & (resumen['TABAQUISMO']=="NO") & (resumen['EPOC']=="NO") & (resumen['ASMA']=="NO") & (resumen['INMUNOSUPRESION']=="NO") & (resumen['HIPERTENSION']=="NO") & (resumen['CARDIOVASCULAR']=="NO") & (resumen['RENAL CRONICA']=="NO") & (resumen['OBESIDAD']=="NO")]
        else:
            resumen = resumen[resumen[condicion]=="SI"]
    resumen = resumen.groupby(['SEXO']).count().drop(['FECHA DEFUNCION','MUNICIPIO RESIDENCIA','FECHA INGRESO','INTUBADO','EDAD','DIABETES','EPOC','ASMA','INMUNOSUPRESION','HIPERTENSION','CARDIOVASCULAR','OBESIDAD','RENAL CRONICA','TABAQUISMO'],axis=1).rename(columns={'ID_REGISTRO':f'{condicion}'}).reset_index()
    enfermedades_genero = enfermedades_genero.merge(resumen, how='left', on='SEXO')
enfermedades_genero = enfermedades_genero.rename(columns={'SEXO':'CONDICION'}).transpose().reset_index()
enfermedades_genero = enfermedades_genero.rename(columns=enfermedades_genero.iloc[0])
enfermedades_genero = enfermedades_genero.drop([0])
display(enfermedades_genero)

          CONDICION   MUJER  HOMBRE
1             TODOS  184583  170908
2     SIN CONDICION  118052  103328
3          DIABETES   17803   17813
4              EPOC    2580    2792
5              ASMA    7752    4477
6   INMUNOSUPRESION    3203    2847
7      HIPERTENSION   25076   24549
8    CARDIOVASCULAR    3697    4085
9          OBESIDAD   27632   22836
10    RENAL CRONICA    3048    3595
11       TABAQUISMO   10966   20649

In [7]:
pd.DataFrame.to_csv(enfermedades_genero,'../static/data/enfermedades_genero.csv',encoding='latin1')
enfermedades_genero.to_json('../static/data/enfermedades_genero.json',orient='records')